name: Auto3
on:
  #schedule:
  #  - cron: '43 1/3 * * *'
  workflow_dispatch:

env:
  RUN_CMD: ${{ secrets.RUN_CMD3 }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          pwsh -EncodedCommand $RUN_CMD
